id     = "pokemon-red-blue"
labels = ["Game", "PokemonSeries", "PokemonRBY"]

[data]
name           = "Pokémon Red, Blue & Yellow"
platform       = "Nintendo Game Boy"
initialRelease = "1996"

boxart = "pokemon-rby-boxart.jpg"
image  = "pokemon-rby-banner.jpg"

worldName = "Kanto"

[data.mapBackground]
color = "#ffffff"

[data.searchLabels]
PokemonRBY    = true
PokemonSeries = true

[data.theme]
mainColor  = "#2f6957"
stylesheet = "gameboy"
